lvl 4.2
P1aner/Javarush2 pull request #11
Opened 2021-12-10 21:41 UTC by P1aner

2021-12-11 09:23 UTC, Catrun404 commented on src/com/javarush/task/task04/task0404/Cat.java
> +/*Напиши код в методе addNewCat, чтобы при его вызове количество котов увеличивалось на 1.
А где вызов метода?

2021-12-11 09:23 UTC, Catrun404 commented on src/com/javarush/task/task04/task0404/Cat.java
> +        Cat.catsCount = Cat.catsCount + 1;
Если обращаешься к статической переменной внутри класса к которому обращаешься, используй this.
```suggestion
        this.catsCount = this.catsCount + 1;
```
```suggestion
        this.catsCount += 1;
```
```suggestion
        this.catsCount++;
```

2021-12-11 09:24 UTC, Catrun404 commented on src/com/javarush/task/task04/task0404/Cat.java
> +        Cat.catsCount = Cat.catsCount + 1;
++ добавляет единицу, как ты уже в курсе (ты используешь это в цикле for-i (i++))

2021-12-11 09:25 UTC, Catrun404 commented on src/com/javarush/task/task04/task0404/Cat.java
> +        Cat.catsCount = Cat.catsCount + 1;
+= прибавляет к переменной слева значение справа

2021-12-11 09:25 UTC, Catrun404 commented on src/com/javarush/task/task04/task0405/Cat.java
> +        Cat.catsCount = catsCount;
this

2021-12-11 09:25 UTC, Catrun404 commented on src/com/javarush/task/task04/task0405/Cat.java
> +
Вызывай метод.

2021-12-11 09:27 UTC, Catrun404 commented on src/com/javarush/task/task04/task0406/Cat.java
> +
Вызывай метод. Здесь ты кстати вдруг начал использовать this (а че раньше то не делал?)

2021-12-11 09:29 UTC, Catrun404 requested changes

2021-12-11 09:29 UTC, Catrun404 commented on src/com/javarush/task/task04/task0407/Solution.java
> +        cat1.count = Cat.count + 1;
Такой метод нужно писать внутри класса. А это костыль, причем плохой. Все каунтеры класса (счетчики) должны вызываться в конструкторе класса. Тут подсказку давать не буду, если только сам не захочешь. В целом - задача не выполнена.

2021-12-11 12:56 UTC, Catrun404 requested changes

2021-12-11 12:56 UTC, Catrun404 commented on src/com/javarush/task/task04/task0407/Solution.java
> +        ;
Че это?

2021-12-11 12:56 UTC, Catrun404 commented on src/com/javarush/task/task04/task0407/Solution.java
> +            Cat.count++;
А зачем тут класс указал? Сат. не нужон

2021-12-11 12:58 UTC, P1aner commented on src/com/javarush/task/task04/task0407/Solution.java
> +            Cat.count++;
-_-

2021-12-12 13:09 UTC, Catrun404 approved these changes

2021-12-12 13:10 UTC, merged