lvl 2 lesson 8
P1aner/Javarush2 pull request #2
Opened 2021-12-07 15:56 UTC by P1aner

Завершенный 2 уровень урок 8

2021-12-07 17:47 UTC, Catrun404 requested changes

2021-12-07 17:47 UTC, Catrun404 commented on src/com/javarush/task/task02/task0214/Solution.java
> +if (a<b)
a < b читается лучше чем a<b, не жмоти пробелы или используй комбинацию Ctrl+Alt+L

2021-12-07 17:47 UTC, Catrun404 commented on src/com/javarush/task/task02/task0214/Solution.java
> +else
Всегда используй {} (braces, фигурные скобки) для if-else стейтмента. В твоем случае можно использовать elvis.

2021-12-07 17:47 UTC, Catrun404 commented on src/com/javarush/task/task02/task0216/Solution.java
> +        if (a<b)
Тоже что и выше.

2021-12-07 18:03 UTC, P1aner commented on src/com/javarush/task/task02/task0214/Solution.java
> +else
не понял

2021-12-07 18:22 UTC, Catrun404 commented on src/com/javarush/task/task02/task0214/Solution.java
> +else
if (a <b) { 
return a;
} else {
return b;
}

2021-12-07 18:25 UTC, Catrun404 commented on src/com/javarush/task/task02/task0214/Solution.java
> +else
A 'Elvis' это к примеру

min = a < b ? a : b;

2021-12-07 22:15 UTC, P1aner commented on src/com/javarush/task/task02/task0214/Solution.java
> +else
в след раз, пока выровнял строки

2021-12-08 09:44 UTC, Catrun404 requested changes

2021-12-08 09:44 UTC, Catrun404 commented on src/com/javarush/task/task02/task0214/Solution.java
> +            min = b;
Все еще не добавлены фигурные скобки.
```suggestion
        int min;
        if (a < b) {
            min = a;
        } else {
            min = b;
        }
```

2021-12-08 09:44 UTC, Catrun404 commented on src/com/javarush/task/task02/task0214/Solution.java
> +            min = b;
И код можно сократить исключив объявление переменной
```suggestion
        if (a < b) {
            return a;
        } else {
            return b;
        }
```

2021-12-08 09:45 UTC, P1aner commented on src/com/javarush/task/task02/task0214/Solution.java
> +            min = b;
outdate изверг

2021-12-08 10:48 UTC, merged