lvl_9.11
P1aner/Javarush2 pull request #37
Opened 2022-01-13 19:43 UTC by P1aner

2022-01-18 05:58 UTC, Catrun404 commented on src/com/javarush/task/task09/task0923/Solution.java
> +        String str2 = "";
Отличные названия переменных (нет)

2022-01-18 05:59 UTC, Catrun404 commented on src/com/javarush/task/task09/task0923/Solution.java
> +                str1 = str1 + symbol + " ";
```suggestion
                str1 += symbol + " ";
```

2022-01-18 06:02 UTC, Catrun404 commented on src/com/javarush/task/task09/task0927/Solution.java
> +            cats.put("кот" + i, new Cat("кот" + i));
лентяй

2022-01-18 06:05 UTC, Catrun404 commented on src/com/javarush/task/task09/task0929/Solution.java
> +        } catch (Exception e) {
```suggestion
        } catch (FileNotFoundException e) {
```

2022-01-18 06:05 UTC, Catrun404 commented on src/com/javarush/task/task09/task0929/Solution.java
> +        } catch (Exception e) {
Ты можешь словить не только его, а пишешь один и тот же комментарий в "лог"

2022-01-18 06:11 UTC, Catrun404 requested changes

2022-01-18 06:11 UTC, Catrun404 commented on src/com/javarush/task/task09/task0930/Solution.java
> +            }
Дублирующийся код нужно выносить в методы. Не засчитано.

2022-01-18 06:11 UTC, Catrun404 commented on src/com/javarush/task/task09/task0930/Solution.java
> +                        if (isNumber(array[j])) {
А слабо проверку в одной строке сделать по двум элементам?

2022-01-18 22:12 UTC, P1aner commented on src/com/javarush/task/task09/task0927/Solution.java
> +            cats.put("кот" + i, new Cat("кот" + i));
и что?

2022-01-18 22:30 UTC, P1aner commented on src/com/javarush/task/task09/task0930/Solution.java
> +            }
исправил на сколько мог

2022-01-22 16:23 UTC, Catrun404 approved these changes

2022-01-23 10:03 UTC, merged